services:
  docker.aspcoreapi:
    image: ${DOCKER_REGISTRY-}dockeraspcoreapi
    container_name:  docker.aspcoreapi.container
    build:
      context: Docker.AspCoreApi
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"

  docker.database:
    image: mcr.microsoft.com/mssql/server:2019-latest  
    container_name: sqlserver-dev
    environment:
      - SA_PASSWORD=YourStrongPassword123!   # Ensure the password meets SQL Server's complexity requirements
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=1434
      - ASPNETCORE_HTTPS_PORTS=1434
      - ACCEPT_EULA=Y                        # Accept SQL Server EULA
      - MSSQL_PID=Express                    # Specify the edition, e.g., Express, Standard, or Enterprise (optional, defaults to Developer)
    ports:
      - "1434:1434"   
    logging:
      driver: "json-file"                    # Use a suitable logging driver for production
    volumes:
      - ./path/to/data:/var/opt/mssql/data    # Persist data to a host directory or volume
      - ./path/to/logs:/var/opt/mssql/log     # Persist logs to a host directory or volume
