@Docker.AspCoreApi_HostAddress = http://3.235.222.128:8080

POST {{Docker.AspCoreApi_HostAddress}}/api/weather
Content-Type: application/json

{
  //Weather
}

###

GET {{Docker.AspCoreApi_HostAddress}}/api/weather

###

GET {{Docker.AspCoreApi_HostAddress}}/api/weather/0

###

DELETE {{Docker.AspCoreApi_HostAddress}}/api/weather/0

###

PUT {{Docker.AspCoreApi_HostAddress}}/api/weather/0
Content-Type: application/json

{
  //Weather
}

###
